var VueApp=new Vue({el:"#v-infoApp",data:{uid:"",photoUrl:"http://img.tgimg.cn/Mywq/default_portrait.png",userName:"",userSex:"",mobile:"",company:"",job:"",experience:"",areaName:"",areaNo:"",typeName:"",typeNo:"",stageName:"",stageNo:"",keyMan:"",keyManNo:"",productName:"",productData:"",client:"",nativePlace:"",nativePlaceNo:"",birthday:"",hobby:"",operatingModule:""}}),getUserInfo=function(a){a.callHandler("TGAppHandler",{eventType:"1",eventParam:{methor:"/Api/GetUserInfo",param:{}}},function(a){if("0x00000000"==
a.state_code&&""!=a.data){var c=a.data.user,d=c.uid,e=c.name||"",f=c.sex||"",m=c.mobile||"",n=c.company||"",q=c.job||"",r=c.experience||"",h=c.business_areas||"",g=c.project_classes||"",k=c.project_stages||"",l=c.key_mans||"";a=c.user_products||"";var s=c.customer_resource?c.customer_resource.join("、"):"",p=c.birth_area||"",t=c.birthday?c.birthday.split("T")[0]:"",c=c.interests?c.interests.join("、"):"";VueApp.userName=e;VueApp.userSex=f;VueApp.mobile=m;VueApp.company=n;VueApp.job=q;VueApp.experience=
r;VueApp.client=s;VueApp.birthday=t;VueApp.hobby=c;""!=d&&(VueApp.uid=d,VueApp.photoUrl="http://user.tgnet.com/User/Face/"+d+"?big=1");if(h){e=[];f=[];for(d=0;d<h.length;d++)e.push(h[d].name),f.push(h[d].no);VueApp.areaName=e.join("、");VueApp.areaNo=f.join(",")}if(g){h=[];e=[];for(d=0;d<g.length;d++)h.push(g[d].name),e.push(g[d].no);VueApp.typeName=h.join("、");VueApp.typeNo=e.join(",")}if(k){g=[];for(d=0;d<k.length;d++)g.push(k[d].name);VueApp.stageName=g.join("、");VueApp.stageNo=k}if(l){k=[];g=[];
for(d=0;d<l.length;d++)k.push(l[d].name),g.push(l[d].no);VueApp.keyMan=k.join("、");VueApp.keyManNo=g.join(",")}if(a){l=[];for(d=0;d<a.length;d++)l.push(a[d].name);VueApp.productName=l.join("、");VueApp.productData=a}p&&(VueApp.nativePlace=p.name,VueApp.nativePlaceNo=p.no)}})};YwqHybrid.WebViewBridge(getUserInfo);
var VueArea=new Vue({el:"#v-infoApp-area",data:{items:"",firstShowNo:""},methods:{changeProvince:function(a){a=$(a.currentTarget);$(".e-area-province li").removeClass("current");a.addClass("current");$(".e-area-city ul").hide();$("#city-"+a.attr("data-province")).show()},changeCityAll:function(a){a=$(a.currentTarget);var b=a.parent("ul"),c=a.attr("data-city");a.hasClass("selected")?($("li",b).removeClass("selected"),$('[data-province="'+c+'"]').removeClass("selected")):($("li",b).addClass("selected"),
$('[data-province="'+c+'"]').addClass("selected"))},changeCity:function(a){var b=$(a.currentTarget);a=b.parent("ul");var c=$("li",a).length,d=b.attr("data-city").substr(0,8);b.hasClass("selected")?b.removeClass("selected"):(b.addClass("selected"),$('[data-province="'+d+'"]').addClass("selected"));b=$(".selected",a).length;$(".e-area-cityAll",a).hasClass("selected")&&b--;c-1==b?$(".e-area-cityAll",a).addClass("selected"):$(".e-area-cityAll",a).removeClass("selected");1>$(".selected",a).length&&$('[data-province="'+
d+'"]').removeClass("selected")},init:function(){var a=$(".e-area-province"),b=$(".e-area-city");if(1>$("li",a).length)setTimeout("VueArea.init()",500);else{var c=VueApp.areaNo.split(","),d={};$(".e-area-content li").removeClass("selected");$("li",a).removeClass("current");if(0<c.length&&""!=c){var e=c[0].substr(0,8);VueArea.firstShowNo=e;$('[data-province="'+e+'"]',a).addClass("current");for(e=0;e<c.length;e++){var f=c[e].substr(0,8);d[f]||($('[data-province="'+f+'"]',a).addClass("selected"),d[f]=
1);12>c[e].length?$("#city-"+c[e]+" li",b).addClass("selected"):$('[data-city="'+c[e]+'"]',b).addClass("selected")}}else VueArea.firstShowNo="",$("li:first",a).addClass("current"),$("ul:first",b).show()}}}}),VueType=new Vue({el:"#v-infoApp-type",data:{items:"",firstShowNo:""},methods:{changeBig:function(a){a=$(a.currentTarget);$(".e-type-big li").removeClass("current");a.addClass("current");$(".e-type-child ul").hide();$("#child-"+a.attr("data-big")).show()},changeChildAll:function(a){a=$(a.currentTarget);
var b=a.parent("ul"),c=a.attr("data-child");a.hasClass("selected")?($("li",b).removeClass("selected"),$('[data-big="'+c+'"]').removeClass("selected")):($("li",b).addClass("selected"),$('[data-big="'+c+'"]').addClass("selected"))},changeChild:function(a){var b=$(a.currentTarget);a=b.parent("ul");var c=$("li",a).length,d=b.attr("data-child").substr(0,12);b.hasClass("selected")?b.removeClass("selected"):(b.addClass("selected"),$('[data-big="'+d+'"]').addClass("selected"));b=$(".selected",a).length;$(".e-type-childAll",
a).hasClass("selected")&&b--;c-1==b?$(".e-type-childAll",a).addClass("selected"):$(".e-type-childAll",a).removeClass("selected");1>$(".selected",a).length&&$('[data-big="'+d+'"]').removeClass("selected")},init:function(){var a=$(".e-type-big"),b=$(".e-type-child");if(1>$("li",a).length)setTimeout("VueType.init()",500);else{var c=VueApp.typeNo.split(","),d={};$(".e-type-content li").removeClass("selected");$("li",a).removeClass("current");if(0<c.length&&""!=c){var e=c[0].substr(0,12);VueType.firstShowNo=
e;$('[data-big="'+e+'"]',a).addClass("current");for(e=0;e<c.length;e++){var f=c[e].substr(0,12);d[f]||($('[data-big="'+f+'"]',a).addClass("selected"),d[f]=1);16>c[e].length?$("#child-"+c[e]+" li",b).addClass("selected"):$('[data-child="'+c[e]+'"]',b).addClass("selected")}}else VueType.firstShowNo="",$("li:first",a).addClass("current"),$("ul:first",b).show()}}}}),VueStage=new Vue({el:"#v-infoApp-stage",data:{items:""},methods:{change:function(a){a=$(a.currentTarget);a.hasClass("selected")?a.removeClass("selected"):
a.addClass("selected")},setMain:function(a){var b=$(a.currentTarget),c=b.parents("ul");b.hasClass("mainStage")||($("a",c).text("设置主要跟进阶段").removeClass("mainStage"),b.text("主要跟进阶段").addClass("mainStage"));a.stopPropagation()},init:function(){this.$nextTick(function(){var a=VueApp.stageNo,b=$(".e-stageModule");$("li",b).removeClass("selected");$("a",b).text("设置主要跟进阶段").removeClass("mainStage");for(var c=0;c<a.length;c++){var d=$('[data-no="'+a[c].no+'"]',b);d.addClass("selected");a[c].main&&$("a",d).text("主要跟进阶段").addClass("mainStage")}})}},
created:function(){this.$http.jsonp("http://api.tgnet.com/CommonData/ProjectStage?deep=1").then(function(a){this.items=a.body.data.items},function(a){console.log(a)})}}),VuekeyMan=new Vue({el:"#v-infoApp-keyMan",data:{items:""},methods:{change:function(a){a=$(a.currentTarget);if(a.hasClass("selected"))a.removeClass("selected");else{var b=a.parents(".e-keyMan-content");5>$(".selected",b).length?a.addClass("selected"):alert("跟进的项目关键人最多选择5个。")}},init:function(){var a=VueApp.keyManNo.split(","),b=$(".e-keyMan-content");
$("a",b).removeClass("selected");for(var c=0;c<a.length;c++)$('[data-no="'+a[c]+'"]',b).addClass("selected")}},created:function(){this.$http.jsonp("Http://api.tgnet.com/CommonData/Keyman").then(function(a){this.items=a.body.data.items},function(a){console.log(a)})}}),VueProductList=new Vue({el:"#v-infoApp-productList",data:{items:[{id:368818,name:"幕墙用铝合金型材",no:"0001000100010004000900010002",class_name:"",level:2,brands:"测试1",is_offer_construction:!0},{id:367120,name:"增压柜无菌室",no:"",class_name:"",level:1,
brands:"dd",is_offer_construction:!1}]},methods:{selected:function(a){if(a=$(a.currentTarget).attr("data-index")||""){var b=VueProductList.items[a];a=b.name||"";var c=b.no||"",d=b.class_name||"",e=b.level||"",f=b.brands||"",b=b.is_offer_construction||!1,m=$(".e-projectEdit-grade"),n=$(window).height();""==a?$(".e-productName").addClass("c-bbb").text("请输入您的产品名称"):$(".e-productName").removeClass("c-bbb").text(a);$(".e-productEdit-no").val(c);$(".e-productEdit-className").val(d);$(".e-brands").val(f);
$("a",m).removeClass("selected");""!=e&&$('[data-no="'+e+'"]',m).addClass("selected");b?$(".e-productEdit-switch").addClass("ui-productEdit-turnOn"):$(".e-productEdit-switch").removeClass("ui-productEdit-turnOn");$(".e-productListModule").hide();$(".e-productEditModule").css("min-height",n).fadeIn()}}}}),VueHobby=new Vue({el:"#v-infoApp-hobby",data:{items:[{title:"运动",subs:"羽毛球 乒乓球 足球 篮球 网球 高尔夫 保龄球 桌球 自行车 游泳 爬山 钓鱼".split(" ")},{title:"休闲",subs:"KTV 麻将 旅游 逛街 电影 酒吧 音乐会 温泉 咖啡厅 游乐场 体育馆 饭店".split(" ")},
{title:"美食",subs:"西餐 清淡 微辣 麻辣 川菜 湘菜 粤菜 东北菜 浙江菜 苏菜 北京菜 西北菜 其他菜".split(" ")}]},methods:{change:function(a){a=$(a.currentTarget);a.hasClass("selected")?a.removeClass("selected"):a.addClass("selected")}}});
$(function(){var a={module:{mian:$(".info-main-module"),modifyName:$(".info-modifyName-module"),modifycompany:$(".info-modifycompany-module"),modifyjob:$(".info-modifyjob-module"),area:$(".info-area-module"),type:$(".e-typeModule"),stage:$(".e-stageModule"),keyMan:$(".e-keyManModule"),hobby:$(".e-hobbyModule"),projectList:$(".e-projectListModule"),projectEdit:$(".e-projectEditModule"),projectSearch:$(".e-projectSearchModule"),client:$(".e-clientModule")},method:{recurInitial:function(){YwqHybrid.navigation.show({leftButton:{type:"2",
image:"back"},title:"个人资料编辑"});document.activeElement.blur()},goback:function(b){b=$(".info-combinationModule");var c=a.module.mian;c.is(":hidden")?(b.hide(),c.fadeIn(),a.method.recurInitial()):YwqHybrid.closeWebView()},saveName:function(){var b=a.module.modifyName,c=a.module.mian,d=$.trim($('[name="v-name"]',b).val());/^[\u4E00-\u9FA5]{2,12}$/.test(d)?ywqHybrid.putUserInfo({value:d,type:1},function(e){VueApp.userName=d;b.hide();c.fadeIn();a.method.recurInitial()}):YwqHybrid.transfer.alert({content:"请输入您的真实姓名，方便您以后的业务合作"})},
saveCompany:function(){var b=a.module.modifycompany,c=a.module.mian,d=$.trim($('[name="v-company"]',b).val());""!=d?ywqHybrid.putUserInfo({value:d,type:3},function(e){VueApp.company=d;b.hide();c.fadeIn();a.method.recurInitial()}):YwqHybrid.transfer.alert("请输入您的真实公司名称，方便您以后的业务合作")},saveJob:function(){var b=a.module.modifyjob,c=a.module.mian,d=$.trim($('[name="v-job"]',b).val());""!=d?ywqHybrid.putUserInfo({value:d,type:2},function(e){VueApp.job=d;b.hide();c.fadeIn();a.method.recurInitial()}):YwqHybrid.transfer.alert("请填写职位")},
save:function(){var b=a.module.modifycompany,c=a.module.modifyjob;a.module.modifyName.is(":visible")?a.method.saveName():b.is(":visible")?a.method.saveCompany():c.is(":visible")&&a.method.saveJob()},switchModule:function(a,c,d,e){var f=$(window).height();d&&("min"==e?a.css("min-height",f):"max"==e?a.css("max-height",f):a.css("height",f));c.hide();a.fadeIn();$("body,html").animate({scrollTop:0},0)},projectBackfill:function(a){var c=a.name||"",d=a.no||"",e=a.class_name||"",f=a.level||"",m=a.brands||
"";a=a.is_offer_construction||!1;var n=$(".e-projectEdit-grade");""==c?$(".e-projecName").addClass("c-bbb").text("请输入您的产品名称"):$(".e-projecName").removeClass("c-bbb").text(c);$(".e-projectEdit-no").val(d);$(".e-projectEdit-className").val(e);$(".e-brands").val(m);$("a",n).removeClass("selected");""!=f&&$('[data-no="'+f+'"]',n).addClass("selected");a?$(".e-projectEdit-switch").addClass("ui-projectEdit-turnOn"):$(".e-projectEdit-switch").removeClass("ui-projectEdit-turnOn")}}};YwqHybrid.registerHandler(function(b){1==
b.eventType&&1==b.eventParam.methor&&(1==b.eventParam.param.buttonClick?a.method.goback():2==b.eventParam.param.buttonClick&&a.method.save())});$(".j-open-modifyNameModule").on("click",function(){var b=a.module.modifyName;a.method.switchModule(b,a.module.mian,!0);YwqHybrid.navigation.show({leftButton:{type:"2",image:"back"},rightButton:{type:"1",content:"确定"},title:"修改姓名"});$("input",b).val(VueApp.userName)});$(".j-open-modifyCompanyModule").on("click",function(){var b=a.module.modifycompany;a.method.switchModule(b,
a.module.mian,!0);YwqHybrid.navigation.show({leftButton:{type:"2",image:"back"},rightButton:{type:"1",content:"确定"},title:"修改公司名称"});$("input",b).val(VueApp.company)});$(".j-open-modifyJobModule").on("click",function(){var b=a.module.modifyjob;a.method.switchModule(b,a.module.mian,!0);YwqHybrid.navigation.show({leftButton:{type:"2",image:"back"},rightButton:{type:"1",content:"确定"},title:"修改职位"});$("input",b).val(VueApp.job)});$(".j-open-modifyAvatarModule").on("click",function(){YwqHybrid.transfer.avatarPlugin(function(a){"0x00000000"==
a.state_code&&(VueApp.photoUrl="http://user.tgnet.com/User/Face/"+VueApp.uid+"?big=1&t="+new Date)})});$(".j-open-modifySexModule").on("click",function(){var a=["男","女","取消"];YwqHybrid.transfer.selectPlugin(a,"请选择性别",function(c){"0x00000000"==c.state_code&&(ywqHybrid.console(a[c.data.buttonClick]),ywqHybrid.putUserInfo({value:a[c.data.buttonClick],type:2},function(a){ywqHybrid.console(a);"0x00000000"==a.state_code&&YwqHybrid.WebViewBridge(getUserInfo)}))})});$(".j-open-modifyExperienceModule").on("click",
function(){YwqHybrid.transfer.pickViewPlugin(1,VueApp.experience,"",function(a){"0x00000000"==a.state_code&&YwqHybrid.WebViewBridge(getUserInfo)})});$(".j-open-modifyNativePlaceModule").on("click",function(){YwqHybrid.transfer.pickViewPlugin(2,VueApp.nativePlaceNo,"",function(a){"0x00000000"==a.state_code&&YwqHybrid.WebViewBridge(getUserInfo)})});$(".j-open-modifyBirthdayModule").on("click",function(){YwqHybrid.transfer.pickViewPlugin(3,VueApp.birthday,"",function(a){"0x00000000"==a.state_code&&YwqHybrid.WebViewBridge(getUserInfo)})});
$(".j-opne-areaModule").on("click",function(){var b=VueArea.items;a.method.switchModule(a.module.area,a.module.mian,!0);""==b?VueArea.$http.jsonp("http://api.tgnet.com/CommonData/Area?deep=2&parent=0001").then(function(a){VueArea.items=a.body.data.items;VueArea.$nextTick(VueArea.init())},function(a){}):VueArea.init()});$(".j-open-typeModule").on("click",function(){var b=VueType.items;a.method.switchModule(a.module.type,a.module.mian,!0);""==b?VueType.$http.jsonp("Http://api.tgnet.com/CommonData/ProjectType").then(function(a){VueType.items=
a.body.data.items;VueType.$nextTick(VueType.init())},function(a){}):VueType.init()});$(".j-opne-stageModule").on("click",function(){a.method.switchModule(a.module.stage,a.module.mian,!0);VueStage.init()});$(".j-open-keyMan").on("click",function(){a.method.switchModule(a.module.keyMan,a.module.mian,!0,"min");VuekeyMan.init()});$(".j-productEdit-grade a").on("click",function(){var a=$(this);a.addClass("selected");a.siblings().removeClass("selected")});$(".j-productEdit-switch").on("click",function(){var a=
$(this);a.hasClass("ui-projectEdit-turnOn")?a.removeClass("ui-projectEdit-turnOn"):a.addClass("ui-projectEdit-turnOn")});$(".j-modify-productName").on("click",function(){var b=$(this).text()||"";$(".e-productSearch-name").val(b);$(".e-productSearch-list").hide();a.method.switchModule(a.module.projectSearch,a.module.projectEdit)});$(".j-open-clientModule").on("click",function(){var b=a.module.client,c=VueApp.client.split("、"),d=$(".e-client-bottom");a.method.switchModule(b,a.module.mian,!0,"min");
0<c.length?d.show():d.hide();$(".e-client-list").html("");for(b=0;b<c.length;b++)$(".e-client-list").append('<li><a href="javascript:;">'+c[b]+"</a></li>")});$(".e-clientInput").on("keyup",function(){var a=$(this),c=$.trim(a.val());15<c.length&&(c=c.substr(0,15));0<c.length?a.next().addClass("c-f90"):a.next().removeClass("c-f90");a.val(c)});$(".j-add-client").on("click",function(){var b=$.trim($(".e-clientInput",a.module.client).val()),c=VueApp.client.split("、"),d=!1;if(""!=b){for(var e=0;e<c.length;e++)b==
c[e]&&(d=!0);d?alert("该客户资源已存在"):a.method.goback()}else alert("请先输入")});$(".e-client-list li").live("click",function(){});$(".j-opne-hobbyModule").on("click",function(){a.method.switchModule(a.module.hobby,a.module.mian,!0,"min");var b=VueApp.hobby.split("、"),c=$(".e-hobbyModule");$("li",c).removeClass("selected");for(var d=0;d<b.length;d++)$('[data-name="'+b[d]+'"]',c).addClass("selected")});$(".j-goback").on("click",function(){a.method.goback()});$(".j-save-name").on("click",function(){var b=a.module;
b.modifyName.is(":visible")?a.method.saveName():b.modifycompany.is(":visible")?a.method.saveCompany():b.modifyjob.is(":visible")&&a.method.saveJob()})});
